version: 2.1
orbs:
  # https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.5.0
jobs:
  test: # This is the name of the job, feel free to change it to better match what you're trying to do!
    parameters:
      python-version:
        type: string
    docker:
      - image: cimg/python:<< parameters.python-version >>
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.dev.txt
      - run:
          name: Run tests
          command: python -m unittest discover mecode/tests

workflows:
  ci: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - test:
          matrix:
            parameters:
              python-version:
                - "2.7"
                - "3.5"
                - "3.6"
                - "3.7"
                - "3.8"
                - "3.9"
                - "3.10"
